# Generated by Django 6.0.1 on 2026-01-27 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('limited_mobility', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['end_date'], name='core_quest_end_dat_3dc5d3_idx'), models.Index(fields=['limited_mobility', 'end_date'], name='core_quest_limited_c712f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('payout', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.quest')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['quest', 'timestamp'], name='core_logger_quest_i_f677dc_idx')],
            },
        ),
    ]
